#!/bin/bash
#
# Copyright 2017, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in
#       the documentation and/or other materials provided with the
#       distribution.
#
#     * Neither the name of the copyright holder nor the names of its
#       contributors may be used to endorse or promote products derived
#       from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
# test/test-strace -- test for strace.ebpf (compare it with system strace)
#

# strace prints raw arguments for all except these syscalls (-e raw=!...):
OPT_STRACE="open,access,stat,lstat,statfs,execve,unlink,chroot,listxattr,\
llistxattr,getxattr,lgetxattr,removexattr,lremovexattr,setxattr,\
lsetxattr,mknod,mknodat,mount,swapon,swapoff,umount2,openat,newfstatat"

PATTERN=./output-strace

OUT_NATIVE_FULL=$PATTERN-native-full.log
OUT_NATIVE_ALL=$PATTERN-native-all.log
OUT_NATIVE=$PATTERN-native.log

OUT_EBPF_FULL=$PATTERN-ebpf-full.log
OUT_EBPF_ALL=$PATTERN-ebpf-all.log
OUT_EBPF=$PATTERN-ebpf.log

DIFF_ALL=$PATTERN-diff-all.log
DIFF=$PATTERN-diff.log

TMP=$(mktemp)

FD="(fd)"
ADDR="(addr)"
FLAGS="(flags)"

TEST_DIR=$(dirname $0)
[ "$TEST_DIR" == "." ] && TEST_DIR=$(pwd)
COMMON=$TEST_DIR/common.sh
[ ! -f $COMMON ] \
	&& echo "Error: missing file $COMMON" \
	&& exit 1
source $COMMON

#
# convert_arg_1 -- convert 1st argument
#
function convert_arg_1() {
	SYSCALL=$1
	ARG1=$2

	# 1st argument
	case "$SYSCALL" in
	# file descriptor can be different
	close|read|write|lseek|fstat|newfstat|ioctl|connect|setsockopt|\
	getsockname|getsockopt|sendto|recvmsg|getdents|fcntl|readlinkat|\
	dup|dup2|fsetxattr|fremovexattr|fadvise64|fstatat|openat|newfstatat)
		echo $FD
		return
		;;
	# address can be different
	brk|capget|capset|mmap|mprotect|munmap|set_robust_list|\
	set_tid_address|futex|uname|poll)
		echo $ADDR
		return
		;;
	# /proc/(pid) can be different
	open|stat|lstat|readlink)
		[[ $ARG1 =~ ^pipe:\[[0-9]+\]$ ]] && ARG1="pipe:[(number)]"
		[[ $ARG1 =~ ^/proc/[0-9]+$ ]] && ARG1="/proc/(pid)"
		[[ $ARG1 =~ ^/proc/[0-9]+/.*$ ]] && ARG1="/proc/(pid)/..."
		echo "$ARG1"
		return
		;;
	# have no arguments at all:
	getuid|geteuid|getpid|gettid)
		echo ""
		return
		;;
	# XXX remove it when the following bug will be fixed:
	# execve sometimes prints pointer instead of path as the 1st argument
	#execve)
	#	echo ""
	#	return
	#	;;
	*)
		echo "$ARG1"
		return
		;;
	esac
}

#
# convert_arg_2 -- convert 2nd argument
#
function convert_arg_2() {
	SYSCALL=$1
	ARG2=$2

	# 1st argument
	case "$SYSCALL" in
	# have no 2nd argument:
	getuid|geteuid|getpid|gettid|\
	brk|uname|chroot|io_destroy|swapoff|set_tid_address|setuid|unlink)
		echo ""
		return
		;;
	# address can be different
	write|read|fstat|arch_prctl|execve|getdents|getrlimit|rt_sigprocmask|\
	rt_sigaction|capset|capget|connect|getsockname|sendto|setitimer|recvmsg)
		echo $ADDR
		return
		;;
	# cannot decode flags
	open|access|stat|lstat|statfs|futex|mknod|umount)
		echo "$FLAGS"
		return
		;;
	*)
		echo "$ARG2"
		return
		;;
	esac
}

#
# convert_n_arg -- convert native argument
#
function convert_n_arg() {
	ARG1=$1
	[[ $ARG1 =~ ^\{ ]] && ARG1=$(echo $ARG1 | cut -d'}' -f1)
	[[ $ARG1 =~ ^\[ ]] && ARG1=$(echo $ARG1 | cut -d']' -f1)
	[[ $ARG1 =~ ^\" ]] \
		&& ARG1=$(echo $ARG1 | cut -d'"' -f2 | cut -d'"' -f1) \
		|| ARG1=$(echo $ARG1 | cut -d"," -f1)
	[[ $ARG1 =~ ^0x ]] && ARG1=$(( $ARG1 + 0))
	[ "$ARG1" == "NULL" ] && ARG1=0
	echo "$ARG1"
}

#
# convert_native -- convert output of system strace
#
function convert_native() {
	FILE=$1

	cat $FILE | \
	while IFS='' read -r line || [[ -n "$line" ]]; do
		# syscall's name
		NAME=$(echo $line | cut -d"(" -f1)
		[ "$NAME" == "umount2" ] && NAME="umount"
		# remove 'new' prefix
		[[ $NAME =~ ^new ]] \
			&& NAME=$(echo $NAME | sed 's/new//g')

		# result
		#n=2
		#TMP="any-string";
		#while [ "$TMP" != "" ]; do
		#	RES=$TMP
		#	TMP=$(echo $line | cut -d"=" -f$n);
		#	n=$(( $n + 1 ))
		#done
		#RES=$(echo $RES | cut -d' ' -f1)

		ARG1=$(echo $line | cut -d"(" -f2 | cut -d")" -f1)

		[[ $line =~ , ]] \
			&& ARG2=$(echo $line | cut -d"," -f2 | cut -d" " -f2 | cut -d")" -f1) \
			|| ARG2=""

		[ "$ARG1" != "" ] \
			&& ARG1=$(convert_n_arg $ARG1) \
			&& ARG1=$(convert_arg_1 $NAME $ARG1)

		[ "$ARG2" != "" ] \
			&& ARG2=$(convert_n_arg $ARG2) \
			&& ARG2=$(convert_arg_2 $NAME $ARG2)

		echo "$NAME $ARG1 $ARG2"
	done
}

#
# convert_ebpf -- convert output of strace.ebpf
#
function convert_ebpf() {
	FILE=$1

	cat $FILE | \
	while IFS='' read -r line || [[ -n "$line" ]]; do
		NAME=$(echo $line | cut -d" " -f5)
		# remove 'new' prefix
		[[ $NAME =~ ^new ]] \
			&& NAME=$(echo $NAME | sed 's/new//g')
		# remove '_pgoff' suffix
		[[ $NAME =~ _pgoff$ ]] \
			&& NAME=$(echo $NAME | sed 's/_pgoff//g')

		# RES=$(echo $line | cut -d" " -f4)

		ARG1=$(echo $line | cut -d" " -f6)
		ARG2=$(echo $line | cut -d" " -f7)

		[[ $ARG1 =~ ^[0F] ]] && ARG1=$(( 0x$ARG1 + 0))
		[[ $ARG2 =~ ^[0F] ]] && ARG2=$(( 0x$ARG2 + 0))

		[ "$ARG1" != "" ] && ARG1=$(convert_arg_1 $NAME $ARG1)
		[ "$ARG2" != "" ] && ARG2=$(convert_arg_2 $NAME $ARG2)

		echo "$NAME $ARG1 $ARG2"
	done
}

#
# test_if_exists -- test if a command exists
#
function test_if_exists() {
	which $1 > /dev/null
	[ $? -ne 0 ] && exit 1
	return 0
}

# temporary debug option for testing converting of outputs
SKIP=0
if [ "$1" == "s" ]; then
	SKIP=1
	shift 1
else
	rm -f $PATTERN*
fi

COMMAND="$*"
if [ "$COMMAND" == "" ]; then
	echo "Usage: $0 <command-to-be-tested>"
	exit 1
fi

test_if_exists $COMMAND 

require_superuser

if [ $SKIP -eq 0 ]; then
	echo "Running system strace ..." >&2
	echo "# sudo strace -e raw=!$OPT_STRACE $COMMAND" >&2
	sudo strace -e raw=\!$OPT_STRACE $COMMAND 1>/dev/null 2>$OUT_NATIVE_FULL
	[ $(cat $OUT_NATIVE_FULL | wc -l) -eq 0 ] && echo "Error: no output of strace" >&2 && exit 1

	echo "Running strace.ebpf ..." >&2
	echo "# sudo bash -c \"$RUN_STRACE -o $OUT_EBPF_FULL $COMMAND\"" >&2
	sudo bash -c "$RUN_STRACE -o $OUT_EBPF_FULL $COMMAND" >/dev/null
	[ $(cat $OUT_EBPF_FULL | wc -l) -eq 0 ] && echo "Error: no output of strace.ebpf" >&2 && exit 1
fi

echo "Converting strace.ebpf's log ($OUT_EBPF_FULL) ..." >&2
grep -v -e "PID_TID" -e "$OUT_EBPF_FULL" $OUT_EBPF_FULL | sort -o $OUT_EBPF_ALL
convert_ebpf $OUT_EBPF_ALL > $OUT_EBPF

echo "Converting strace's log ($OUT_NATIVE_FULL) ..." >&2
grep -v -e "exit_group" -e "exited with" $OUT_NATIVE_FULL | grep "(" > $OUT_NATIVE_ALL
convert_native $OUT_NATIVE_ALL > $OUT_NATIVE

diff -y $OUT_NATIVE $OUT_EBPF > $DIFF_ALL
ERRORS=$(grep -e '|' -e '<' -e '>' $DIFF_ALL | tee $TMP | wc -l)

if [ $ERRORS -eq 0 ]; then
	echo "Test passed."
	RV=0
else
	echo "Test FAILED!"
	echo
	echo "Following $ERRORS line(s) differ:"
	echo "--- (system strace) -------------------------------------- | --- (strace.ebpf) ----------------------------------------"
	cat $TMP | tee $DIFF
	echo "--- (system strace) -------------------------------------- | --- (strace.ebpf) ----------------------------------------"
	echo "($ERRORS line(s) differ)"
	echo
	echo "Full diff: $DIFF_ALL"
	echo "Full strace log: $OUT_NATIVE_ALL"
	echo "Full strace.ebpf log: $OUT_EBPF_ALL"
	echo
	echo "Tracing of the command '$COMMAND' FAILED."
	echo
	RV=1
fi

rm -f $TMP

exit $RV
